package com.selfflow.app.presentation.theme

import androidx.compose.ui.graphics.Color

// Airbnb-inspired warm palette
val primaryLight = Color(0xFFE74C3C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE5E2)
val onPrimaryContainerLight = Color(0xFF4A0F0A)
val secondaryLight = Color(0xFF00A699)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB2F0EA)
val onSecondaryContainerLight = Color(0xFF00332F)
val tertiaryLight = Color(0xFFFFA726)
val onTertiaryLight = Color(0xFF2A1800)
val tertiaryContainerLight = Color(0xFFFFE8C8)
val onTertiaryContainerLight = Color(0xFF4A2A00)
val errorLight = Color(0xFFC62828)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7F7F7)
val onBackgroundLight = Color(0xFF222222)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF222222)
val surfaceVariantLight = Color(0xFFF0F0F0)
val onSurfaceVariantLight = Color(0xFF717171)
val outlineLight = Color(0xFFB0B0B0)

val primaryDark = Color(0xFFFF6B6B)
val onPrimaryDark = Color(0xFF3D0000)
val primaryContainerDark = Color(0xFF7A1F1F)
val onPrimaryContainerDark = Color(0xFFFFDAD6)
val secondaryDark = Color(0xFF4DB6AC)
val onSecondaryDark = Color(0xFF00332F)
val secondaryContainerDark = Color(0xFF004F49)
val onSecondaryContainerDark = Color(0xFFB2F0EA)
val tertiaryDark = Color(0xFFFFB74D)
val onTertiaryDark = Color(0xFF4A2A00)
val tertiaryContainerDark = Color(0xFF6B3D00)
val onTertiaryContainerDark = Color(0xFFFFE8C8)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE5E5E5)
val surfaceDark = Color(0xFF1E1E1E)
val onSurfaceDark = Color(0xFFE5E5E5)
val surfaceVariantDark = Color(0xFF2C2C2C)
val onSurfaceVariantDark = Color(0xFFB0B0B0)
val outlineDark = Color(0xFF606060)
